numpy is the fundamental python library that provides support for 1D arrays (vector) and matricesalomg with implemented mathematical  functions 



In [ ]:
mylist=[1,2,3]
print(mylist)
type(mylist)
type(mylist[0])

[1, 2, 3]


int

In [2]:
import numpy as np
myNplist=np.array(mylist)
myNplist

array([1, 2, 3])

In [6]:
sample_list=(([1,2,3],[4,5,6],[7,8,9]))
type(sample_list)
sample_matrix=np.array(sample_list)
sample_list


([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [12]:
a=np.arange(2,20,3)

In [20]:
b=np.arange(25)
b.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.randn(3,4)

array([[ 0.06726717, -0.746489  , -0.60071002,  0.26086037],
       [ 0.51588508, -0.15616958,  0.02174661, -1.88161072],
       [-0.98586453, -0.92986786, -0.36908626, -0.72731565]])

In [31]:
v=np.random.randn(3,4)
v

array([[-1.43382474, -0.67120645, -0.31325794, -0.47690368],
       [ 0.16238501,  0.1970084 , -0.26456448,  1.41577282],
       [ 0.31039316,  0.54527274,  0.11820436, -0.57533397]])

In [32]:
v.shape

(3, 4)

In [33]:
v.dtype

dtype('float64')

In [35]:
t=np.random.randint(10,50,1)
t

array([23], dtype=int32)

In [37]:
t=np.random.randint(10,50,5)
t

array([47, 24, 14, 41, 15], dtype=int32)

In [39]:
t.max()

np.int32(47)