In [1]:
import numpy as np

In [2]:
a=np.arange(2,20,5)

In [3]:
a.max()

np.int64(17)

In [4]:
a

array([ 2,  7, 12, 17])

In [6]:
s_arr=np.arange(1,11)
s_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
s_arr[2]

np.int64(3)

In [8]:
s_arr[0:4]

array([1, 2, 3, 4])

In [22]:
sample_mat=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(sample_mat)

array([1, 2, 3])

In [14]:
sample_mat[0]

array([1, 2, 3])

In [16]:
sample_mat[0,2]

np.int64(3)

In [17]:
sample_mat[1:2]

array([[4, 5, 6]])

In [ ]:
sample_mat[:2,1:]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
sample_mat[1,1:]


array([5, 6])

In [20]:
sample_mat[0:5]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
s_arr[0:3]=400
s_arr

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [28]:
print(id(s_arr[0:5]))
slice_s_arr=s_arr[0:5]
s=slice_s_arr
print(id(slice_s_arr))
print(id(s_arr))
print(id(s))


2865337307504
2865336876368
2865336450672
2865336876368


In [31]:
slice_s_arr[:]=100
slice_s_arr


array([100, 100, 100, 100, 100])

In [32]:
s_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [34]:
s_arr_copy=s_arr.copy()
s_arr_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [35]:
s_arr_copy[:]=300


difference between range and arange fucntipn 

In [37]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
boolean_arr=arr>5
print(boolean_arr)
type(boolean_arr)

[False False False False False  True  True  True  True  True]


numpy.ndarray

In [52]:
b=np.arange(1,20,5)
numpy.add(a,b)
a

NameError: name 'numpy' is not defined

In [45]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
a


array([ 2,  7, 12, 17])

In [53]:
np.add(a,b)


array([ 3, 13, 23, 33])

In [54]:
b

array([ 1,  6, 11, 16])

In [56]:
b=np.dot(a,100)
b

array([ 200,  700, 1200, 1700])

In [70]:
c=np.arange(2,20,6)
c
d=np.arange(3,21,6)
d


array([ 3,  9, 15])

In [71]:
e=np.cross(c,d)
e

array([-6, 12, -6])

In [72]:
#implement bubble sort in python

#3d vectors
a=np.array([1,2,3])
b=np.array([4,5,6])
cp_3d=np.cross(a,b)
print(f'cross prodcut of 3d vectors:{cp_3d}')



cross prodcut of 3d vectors:[-3  6 -3]


In [73]:
#2d vector
x=np.array([1,2])
y=np.array([3,4])
cp_2d=np.cross(x,y)
print(f'cross prodcut of 2d vectors:{cp_2d}')



cross prodcut of 2d vectors:-2


C:\Users\asus\AppData\Local\Temp\ipykernel_9352\1045807934.py:4: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cp_2d=np.cross(x,y)


In [74]:
print(a/a)
print(1/a)


[1. 1. 1.]
[1.         0.5        0.33333333]


In [77]:

coefficient=[12,3,4,5,10]
polyexp=np.poly1d(coefficient)
print('type pf polynomial=',type(polyexp))
print('polynomial expression is:',polyexp)
print(polyexp)
x=2
result=polyexp(x)
print(result)
print('------------------')

type pf polynomial= <class 'numpy.poly1d'>
polynomial expression is:     4     3     2
12 x + 3 x + 4 x + 5 x + 10
    4     3     2
12 x + 3 x + 4 x + 5 x + 10
252
------------------


In [80]:
a=np.matrix(((10,20,30,40),(50,60,70,80)))
a

matrix([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [82]:
b=np.transpose(a)
b

matrix([[10, 50],
        [20, 60],
        [30, 70],
        [40, 80]])

In [83]:
a=np.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(2,3,4,5)))
b=np.hsplit(a,2)
print('a \n',a)
print('b \n',b)
c=b[0]
d=b[1]
print('c \n',c)
print('d \n',d)
e=np.vsplit(c,2)
f=np.vsplit(d,2)
print('e1 \n',e[0])



a 
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [  2   3   4   5]]
b 
 [matrix([[ 10,  20],
        [ 50,  60],
        [ 90, 100],
        [  2,   3]]), matrix([[ 30,  40],
        [ 70,  80],
        [110, 120],
        [  4,   5]])]
c 
 [[ 10  20]
 [ 50  60]
 [ 90 100]
 [  2   3]]
d 
 [[ 30  40]
 [ 70  80]
 [110 120]
 [  4   5]]
e1 
 [[10 20]
 [50 60]]
